In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
w = [[1,2,3],[4,5,6],[7,8,9]]
x = [[1],[2],[3]]

In [3]:
w_torch = torch.FloatTensor(w)

x_torch = torch.FloatTensor(x)

b_torch = torch.ones(3,1)

output = torch.matmul(w_torch, x_torch) + b_torch # computing mx + b

In [4]:
output

tensor([[15.],
        [33.],
        [51.]])

In [5]:
output.shape

torch.Size([3, 1])

In [12]:
# numpy to torch and vice-versa

np_array = np.random.random((3, 4))

torch_tensor = torch.FloatTensor(np_array)

np_torch = torch_tensor.numpy()

In [13]:
np_array

array([[0.41724825, 0.5029771 , 0.09062142, 0.91337149],
       [0.45325667, 0.62576513, 0.14648372, 0.89584462],
       [0.28906318, 0.28927851, 0.63028255, 0.24913278]])

In [14]:
torch_tensor

tensor([[0.4172, 0.5030, 0.0906, 0.9134],
        [0.4533, 0.6258, 0.1465, 0.8958],
        [0.2891, 0.2893, 0.6303, 0.2491]])

In [15]:
np_torch

array([[0.41724825, 0.5029771 , 0.09062142, 0.9133715 ],
       [0.45325667, 0.62576514, 0.14648372, 0.89584464],
       [0.2890632 , 0.2892785 , 0.6302826 , 0.24913278]], dtype=float32)

In [16]:
y = torch.rand(4,5)

In [17]:
y

tensor([[0.1306, 0.9055, 0.1409, 0.0041, 0.4025],
        [0.4864, 0.9706, 0.6406, 0.1611, 0.3400],
        [0.2000, 0.5607, 0.1009, 0.4942, 0.1544],
        [0.3582, 0.1107, 0.3262, 0.9547, 0.0736]])

In [19]:
# operations on y tensor

print(y * 10)
print((y+1)**2)
print(y+y)

tensor([[1.3063, 9.0548, 1.4089, 0.0406, 4.0251],
        [4.8637, 9.7056, 6.4056, 1.6110, 3.4001],
        [2.0000, 5.6067, 1.0089, 4.9422, 1.5443],
        [3.5820, 1.1074, 3.2622, 9.5467, 0.7357]])
tensor([[1.2783, 3.6309, 1.3016, 1.0081, 1.9670],
        [2.2093, 3.8831, 2.6914, 1.3482, 1.7956],
        [1.4400, 2.4357, 1.2120, 2.2327, 1.3327],
        [1.8447, 1.2338, 1.7588, 3.8207, 1.1526]])
tensor([[0.2613, 1.8110, 0.2818, 0.0081, 0.8050],
        [0.9727, 1.9411, 1.2811, 0.3222, 0.6800],
        [0.4000, 1.1213, 0.2018, 0.9884, 0.3089],
        [0.7164, 0.2215, 0.6524, 1.9093, 0.1471]])


In [20]:
print(y/(y+1))

tensor([[0.1155, 0.4752, 0.1235, 0.0040, 0.2870],
        [0.3272, 0.4925, 0.3905, 0.1387, 0.2537],
        [0.1667, 0.3592, 0.0916, 0.3308, 0.1338],
        [0.2637, 0.0997, 0.2460, 0.4884, 0.0685]])


In [21]:
torch.sqrt(y**2)

tensor([[0.1306, 0.9055, 0.1409, 0.0041, 0.4025],
        [0.4864, 0.9706, 0.6406, 0.1611, 0.3400],
        [0.2000, 0.5607, 0.1009, 0.4942, 0.1544],
        [0.3582, 0.1107, 0.3262, 0.9547, 0.0736]])

In [22]:
y.mean(), y.sum(), y.min(), y.max(), y.std()

(tensor(0.3758),
 tensor(7.5158),
 tensor(0.0041),
 tensor(0.9706),
 tensor(0.3010))

In [26]:
# tensor operations

tensor_1 = torch.rand(3,3,3)
t_2 = torch.rand(3,3,3)

tensor_1
t_2

tensor([[[0.6432, 0.2862, 0.2442],
         [0.3801, 0.0473, 0.9661],
         [0.9003, 0.1032, 0.4013]],

        [[0.4805, 0.6515, 0.2758],
         [0.9335, 0.5082, 0.3206],
         [0.6677, 0.8822, 0.7916]],

        [[0.7833, 0.9964, 0.7489],
         [0.1741, 0.2913, 0.8591],
         [0.1712, 0.4589, 0.9785]]])

In [27]:
tensor_1 + t_2

tensor([[[1.2195, 0.6420, 1.1420],
         [0.6418, 0.1987, 1.0010],
         [0.9508, 1.0082, 1.3274]],

        [[1.3828, 0.6995, 0.9831],
         [1.6450, 0.7714, 0.4441],
         [1.6364, 1.1164, 1.0462]],

        [[0.8705, 1.1353, 1.3873],
         [0.5640, 0.4905, 1.4265],
         [0.4823, 1.0147, 1.9193]]])

In [28]:
# batch multiplication on 3d tensor

torch.bmm(tensor_1, t_2)

tensor([[[1.3142, 0.2744, 0.8448],
         [0.2573, 0.0857, 0.2242],
         [1.2102, 0.1529, 1.2584]],

        [[0.9506, 1.2362, 0.8241],
         [0.6700, 0.7062, 0.3784],
         [0.8541, 0.9748, 0.5438]],

        [[0.2018, 0.4203, 0.8093],
         [0.4372, 0.7069, 1.0183],
         [0.5015, 0.9036, 1.6311]]])

In [30]:
t_3 = torch.rand(2,4,5)
t_3

tensor([[[0.3781, 0.9628, 0.8833, 0.5191, 0.4057],
         [0.8043, 0.3238, 0.5988, 0.4047, 0.4053],
         [0.8764, 0.1038, 0.4806, 0.4865, 0.5102],
         [0.2534, 0.7790, 0.2823, 0.1326, 0.7678]],

        [[0.3752, 0.3494, 0.9181, 0.5771, 0.0909],
         [0.9665, 0.6131, 0.1544, 0.6773, 0.2621],
         [0.6622, 0.8263, 0.6126, 0.0087, 0.4188],
         [0.0261, 0.4140, 0.8563, 0.2454, 0.6840]]])

In [31]:
t_3.shape

torch.Size([2, 4, 5])

In [33]:
t_3.transpose(0, 2), t_3.transpose(0, 2).shape

(tensor([[[0.3781, 0.3752],
          [0.8043, 0.9665],
          [0.8764, 0.6622],
          [0.2534, 0.0261]],
 
         [[0.9628, 0.3494],
          [0.3238, 0.6131],
          [0.1038, 0.8263],
          [0.7790, 0.4140]],
 
         [[0.8833, 0.9181],
          [0.5988, 0.1544],
          [0.4806, 0.6126],
          [0.2823, 0.8563]],
 
         [[0.5191, 0.5771],
          [0.4047, 0.6773],
          [0.4865, 0.0087],
          [0.1326, 0.2454]],
 
         [[0.4057, 0.0909],
          [0.4053, 0.2621],
          [0.5102, 0.4188],
          [0.7678, 0.6840]]]),
 torch.Size([5, 4, 2]))

In [34]:
tensor = torch.rand(2,3,1,4)

In [36]:
tensor

tensor([[[[7.0144e-01, 7.0257e-01, 1.6317e-01, 7.8449e-01]],

         [[3.3370e-01, 7.5643e-01, 7.8288e-01, 5.7935e-01]],

         [[1.8213e-01, 9.5737e-01, 3.4837e-01, 7.8082e-01]]],


        [[[4.4619e-01, 5.9043e-01, 9.0258e-01, 2.1477e-02]],

         [[3.7656e-03, 4.3172e-01, 6.1694e-01, 9.1622e-01]],

         [[7.5757e-01, 1.7881e-04, 8.2825e-02, 4.0574e-01]]]])

In [35]:
tensor[-1]

tensor([[[4.4619e-01, 5.9043e-01, 9.0258e-01, 2.1477e-02]],

        [[3.7656e-03, 4.3172e-01, 6.1694e-01, 9.1622e-01]],

        [[7.5757e-01, 1.7881e-04, 8.2825e-02, 4.0574e-01]]])

In [38]:
tensor[0, 1]

tensor([[0.3337, 0.7564, 0.7829, 0.5794]])

In [39]:
tensor[:, 1, 0, 2]

tensor([0.7829, 0.6169])

In [41]:
tensor.shape

torch.Size([2, 3, 1, 4])

In [42]:
tensor.size()

torch.Size([2, 3, 1, 4])

In [43]:
tensor.numel()

24

In [44]:
tensor.ndim

4

In [46]:
tensor = torch.rand(3,5,3,2)

In [47]:
tensor.reshape(3,30)

tensor([[0.2955, 0.8701, 0.7172, 0.4005, 0.4127, 0.4665, 0.8461, 0.7130, 0.6783,
         0.6415, 0.1778, 0.3925, 0.8658, 0.8954, 0.5397, 0.8930, 0.6265, 0.9234,
         0.0782, 0.0320, 0.6353, 0.8273, 0.6022, 0.2234, 0.5415, 0.1171, 0.6505,
         0.5007, 0.8814, 0.5048],
        [0.9890, 0.2645, 0.5397, 0.7442, 0.6170, 0.7856, 0.1143, 0.1155, 0.1082,
         0.5706, 0.2632, 0.6501, 0.5876, 0.1606, 0.6530, 0.0968, 0.4139, 0.1769,
         0.5728, 0.9525, 0.8470, 0.2825, 0.7095, 0.2893, 0.5719, 0.7392, 0.2025,
         0.9667, 0.9147, 0.2152],
        [0.4739, 0.3377, 0.3258, 0.7622, 0.3641, 0.5506, 0.9637, 0.8450, 0.9476,
         0.6808, 0.1381, 0.7038, 0.0850, 0.8402, 0.8389, 0.4287, 0.1009, 0.3874,
         0.1672, 0.1413, 0.5224, 0.3500, 0.0255, 0.5054, 0.8814, 0.6597, 0.1130,
         0.1278, 0.7585, 0.5445]])

In [48]:
tensor.flatten()

tensor([0.2955, 0.8701, 0.7172, 0.4005, 0.4127, 0.4665, 0.8461, 0.7130, 0.6783,
        0.6415, 0.1778, 0.3925, 0.8658, 0.8954, 0.5397, 0.8930, 0.6265, 0.9234,
        0.0782, 0.0320, 0.6353, 0.8273, 0.6022, 0.2234, 0.5415, 0.1171, 0.6505,
        0.5007, 0.8814, 0.5048, 0.9890, 0.2645, 0.5397, 0.7442, 0.6170, 0.7856,
        0.1143, 0.1155, 0.1082, 0.5706, 0.2632, 0.6501, 0.5876, 0.1606, 0.6530,
        0.0968, 0.4139, 0.1769, 0.5728, 0.9525, 0.8470, 0.2825, 0.7095, 0.2893,
        0.5719, 0.7392, 0.2025, 0.9667, 0.9147, 0.2152, 0.4739, 0.3377, 0.3258,
        0.7622, 0.3641, 0.5506, 0.9637, 0.8450, 0.9476, 0.6808, 0.1381, 0.7038,
        0.0850, 0.8402, 0.8389, 0.4287, 0.1009, 0.3874, 0.1672, 0.1413, 0.5224,
        0.3500, 0.0255, 0.5054, 0.8814, 0.6597, 0.1130, 0.1278, 0.7585, 0.5445])

In [49]:
tensor.reshape(10, -1)

tensor([[0.2955, 0.8701, 0.7172, 0.4005, 0.4127, 0.4665, 0.8461, 0.7130, 0.6783],
        [0.6415, 0.1778, 0.3925, 0.8658, 0.8954, 0.5397, 0.8930, 0.6265, 0.9234],
        [0.0782, 0.0320, 0.6353, 0.8273, 0.6022, 0.2234, 0.5415, 0.1171, 0.6505],
        [0.5007, 0.8814, 0.5048, 0.9890, 0.2645, 0.5397, 0.7442, 0.6170, 0.7856],
        [0.1143, 0.1155, 0.1082, 0.5706, 0.2632, 0.6501, 0.5876, 0.1606, 0.6530],
        [0.0968, 0.4139, 0.1769, 0.5728, 0.9525, 0.8470, 0.2825, 0.7095, 0.2893],
        [0.5719, 0.7392, 0.2025, 0.9667, 0.9147, 0.2152, 0.4739, 0.3377, 0.3258],
        [0.7622, 0.3641, 0.5506, 0.9637, 0.8450, 0.9476, 0.6808, 0.1381, 0.7038],
        [0.0850, 0.8402, 0.8389, 0.4287, 0.1009, 0.3874, 0.1672, 0.1413, 0.5224],
        [0.3500, 0.0255, 0.5054, 0.8814, 0.6597, 0.1130, 0.1278, 0.7585, 0.5445]])

In [50]:
# adding empty dimension to equal other dimensions for opertions.

t = torch.rand(3, 2)

print(t.shape)

torch.Size([3, 2])


In [51]:
t.unsqueeze(2).shape

torch.Size([3, 2, 1])

In [52]:
t.unsqueeze(1).shape

torch.Size([3, 1, 2])

In [53]:
t = torch.rand(1,3,1,2)

In [54]:
t.shape

torch.Size([1, 3, 1, 2])

In [55]:
t.squeeze(2).shape

torch.Size([1, 3, 2])

In [57]:
t.squeeze(0).shape

torch.Size([3, 1, 2])

In [62]:
t.squeeze().shape

torch.Size([3, 2])

In [63]:
t1 = torch.rand(1,4,3,1)
t2 = torch.rand(3,4,1,4)

In [68]:
t1.shape

torch.Size([1, 4, 3, 1])

In [70]:
t2.shape

torch.Size([3, 4, 1, 4])

In [71]:
t = t1 + t2

In [72]:
t.shape

torch.Size([3, 4, 3, 4])

In [6]:
## using squeeze and unsqueeze we can add and remove one or more dimensions to adjust the overall dimensions. 
## We add new dimension to equal with others tensors, this is done by adding zeros in that dimesnion.

### for training and model building we use these functions.

- nn.Linear() # linear model

- nn.sigmoid() # sigmoid model

- nn.Sequential() # building things sequentially

- nn.MSELoss() # MSE loss

- nn.BCELoss() # Binary cross entropy loss

- torch.optim.SGD() # Stochistic gradient loss

- torch.optim.Adam() # adam loss funtion a special case of SGD

- optimizer.zero_grad() # zeroing the gradients 

- loss.backward() # calculating the gradients

- optimizer.step() # updating the parameters on current gradient iteration

- model.save_dict() # Loading the current state parameters and weights of our model

- torch.save() # saving the model

- torch.load_state_dict() loading the model