In [2]:
from transformers import AutoTokenizer

In [3]:
checkpoint = "prajjwal1/bert-tiny"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

config.json:   0%|          | 0.00/285 [00:00<?, ?B/s]

C:\Users\trinity\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:148: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\trinity\.cache\huggingface\hub\models--prajjwal1--bert-tiny. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [4]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]

In [5]:
inputs = tokenizer(raw_inputs, padding = True, truncation=True, return_tensors='pt')

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


In [6]:
print(inputs)

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [7]:
from transformers import AutoModel

In [8]:
model = AutoModel.from_pretrained(checkpoint)

pytorch_model.bin:   0%|          | 0.00/17.8M [00:00<?, ?B/s]

In [9]:
import torchinfo

In [13]:
torchinfo.summary(model)

Layer (type:depth-idx)                             Param #
BertModel                                          --
├─BertEmbeddings: 1-1                              --
│    └─Embedding: 2-1                              3,906,816
│    └─Embedding: 2-2                              65,536
│    └─Embedding: 2-3                              256
│    └─LayerNorm: 2-4                              256
│    └─Dropout: 2-5                                --
├─BertEncoder: 1-2                                 --
│    └─ModuleList: 2-6                             --
│    │    └─BertLayer: 3-1                         198,272
│    │    └─BertLayer: 3-2                         198,272
├─BertPooler: 1-3                                  --
│    └─Linear: 2-7                                 16,512
│    └─Tanh: 2-8                                   --
Total params: 4,385,920
Trainable params: 4,385,920
Non-trainable params: 0

In [14]:
outputs = model(**inputs)

In [15]:
outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-1.5472e+00,  3.7050e-01, -4.0959e+00,  ..., -9.8540e-02,
          -1.5862e-01,  3.1613e-01],
         [-1.5180e+00,  4.4641e-01, -1.9458e-01,  ..., -2.2864e+00,
          -5.5999e-01,  3.8482e-01],
         [-6.6889e-01, -5.1541e-01, -7.2796e-01,  ..., -1.4184e+00,
          -8.3270e-01,  2.3263e+00],
         ...,
         [-8.5156e-01, -2.6314e-01, -1.3632e+00,  ..., -1.8184e+00,
          -1.5837e-01, -5.7638e-01],
         [-9.2688e-01,  4.2817e-01, -4.1839e-01,  ..., -1.3705e+00,
          -5.8617e-01, -5.4587e-02],
         [-2.4657e+00,  5.2421e-01, -2.2240e-01,  ..., -1.4647e+00,
          -1.3668e-01,  1.0676e+00]],

        [[-1.6088e+00,  3.0306e-02, -3.0148e+00,  ...,  2.0669e-01,
          -8.7602e-01,  5.4367e-01],
         [-1.5096e+00, -5.0517e-01,  3.4708e-01,  ..., -8.8639e-01,
          -7.7178e-01,  1.1090e+00],
         [-1.8140e+00, -2.5889e-01, -4.6013e-01,  ..., -1.0221e-01,
          -1.

In [18]:
outputs.last_hidden_state.shape

torch.Size([2, 16, 128])

In [21]:
from transformers import AutoModelForSequenceClassification

In [22]:
cal_model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at prajjwal1/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [23]:
cal_output = cal_model(**inputs)

In [24]:
cal_output

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.0694, -0.2123],
        [-0.0648, -0.1701]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [27]:
print(cal_output.logits.shape)

torch.Size([2, 2])


In [29]:
cal_output.logits

tensor([[ 0.0694, -0.2123],
        [-0.0648, -0.1701]], grad_fn=<AddmmBackward0>)

In [30]:
import torch

In [33]:
prediction = torch.nn.functional.softmax(cal_output.logits, dim = -1)

In [34]:
prediction

tensor([[0.5700, 0.4300],
        [0.5263, 0.4737]], grad_fn=<SoftmaxBackward0>)

In [35]:
cal_model.config.id2label

{0: 'LABEL_0', 1: 'LABEL_1'}

In [36]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [39]:
checkpoint = "prajjwal1/bert-tiny"

In [40]:
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [42]:
raw_inputs = ["I really appreciate your hard work and dedication to this project.", 
          "I really appreciate your hard work and dedication to this project."]

In [43]:
tokenized_input = tokenizer(raw_inputs, padding = True, truncation=True, return_tensors='pt' )

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


In [44]:
tokenized_input

{'input_ids': tensor([[  101,  1045,  2428,  9120,  2115,  2524,  2147,  1998, 12276,  2000,
          2023,  2622,  1012,   102],
        [  101,  1045,  2428,  9120,  2115,  2524,  2147,  1998, 12276,  2000,
          2023,  2622,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [45]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at prajjwal1/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [46]:
outputs = model(**tokenized_input)

In [51]:
outputs # logits

SequenceClassifierOutput(loss=None, logits=tensor([[-0.1732, -0.1259],
        [-0.1732, -0.1259]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [52]:
import torch

In [53]:
final_output = torch.nn.functional.softmax(outputs.logits, dim = -1 )

In [54]:
final_output

tensor([[0.4882, 0.5118],
        [0.4882, 0.5118]], grad_fn=<SoftmaxBackward0>)

In [55]:
model.config.id2label

{0: 'LABEL_0', 1: 'LABEL_1'}

In [56]:
model.save_pretrained('my-smallest-model')

In [57]:
encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102],
]

In [62]:
inputs = torch.tensor(encoded_sequences)

In [64]:
op = model(inputs)

In [67]:
torch.nn.functional.softmax(op.logits, dim = -1)

tensor([[0.4959, 0.5041],
        [0.4742, 0.5258],
        [0.4906, 0.5094]], grad_fn=<SoftmaxBackward0>)

In [69]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(ids)
print(input_ids)
# This line will fail.
model(input_ids)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at prajjwal1/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tensor([ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
         2026,  2878,  2166,  1012])


IndexError: too many indices for tensor of dimension 1

In [70]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence, return_tensors = 'pt')
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(ids)
print(input_ids)
# This line will fail.
model(input_ids)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at prajjwal1/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tensor([ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
         2026,  2878,  2166,  1012])


IndexError: too many indices for tensor of dimension 1

In [71]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)

input_ids = torch.tensor([ids])
print("Input IDs:", input_ids)

output = model(input_ids)
print("Logits:", output.logits)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at prajjwal1/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Input IDs: tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits: tensor([[-0.1102, -0.1413]], grad_fn=<AddmmBackward0>)


In [80]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)

batch = [ids, ids]

input_ids = torch.tensor(batch)
print("Input IDs:", input_ids)

output = model(input_ids)
print("Logits:", output.logits)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at prajjwal1/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Input IDs: tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012],
        [ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits: tensor([[ 0.0776, -0.2875],
        [ 0.0776, -0.2875]], grad_fn=<AddmmBackward0>)


In [81]:
seq1 = [[200, 200, 200]]

seq2 = [[200, 200]]

batched = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id]
]

print(model(torch.tensor(seq1)).logits)
print(model(torch.tensor(seq2)).logits)
print(model(torch.tensor(batched)).logits)

tensor([[ 0.0095, -0.2133]], grad_fn=<AddmmBackward0>)
tensor([[ 0.0091, -0.2052]], grad_fn=<AddmmBackward0>)
tensor([[ 0.0095, -0.2133],
        [ 0.0015, -0.2680]], grad_fn=<AddmmBackward0>)


In [82]:
attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]

outputs = model(torch.tensor(batched), attention_mask=torch.tensor(attention_mask))
print(outputs.logits)

tensor([[ 0.0095, -0.2133],
        [ 0.0091, -0.2052]], grad_fn=<AddmmBackward0>)


In [117]:
first = "I've been waiting for a HuggingFace course my whole life"
second = "I hate this so much!"

In [118]:
raw_token1 = tokenizer.tokenize(first)
raw_token2 = tokenizer.tokenize(second)

In [119]:
token1 = tokenizer.convert_tokens_to_ids(raw_token1)
token2 = tokenizer.convert_tokens_to_ids(raw_token2)

In [120]:
# token1, token2

In [121]:
print(model(torch.tensor([token1])).logits)

tensor([[ 0.0784, -0.2834]], grad_fn=<AddmmBackward0>)


In [122]:
print(model(torch.tensor([token2])).logits)

tensor([[ 0.1294, -0.1849]], grad_fn=<AddmmBackward0>)


In [135]:
batched = [
    [token1],
    [token2]
]

In [136]:
print(model(torch.tensor(batched)).logits)

ValueError: expected sequence of length 13 at dim 2 (got 6)